In [1]:
#1. Reshape a 1D array of 12 elements into a 3x4 matrix

In [2]:
import numpy as np

In [3]:
array_1d = np.arange(12)  
matrix_3x4 = array_1d.reshape(3, 4)

print("3x4 Matrix:")
print(matrix_3x4)

3x4 Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
#2. Flatten a 3x3 matrix into a 1D array

In [5]:
matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

flattened_array = matrix_3x3.flatten()

print("Flattened Array:")
print(flattened_array)

Flattened Array:
[1 2 3 4 5 6 7 8 9]


In [6]:
#3. Stack two 3x3 matrices horizontally and vertically

In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])


v_stack = np.vstack((a, b))
print("Vertical Stack:")
print(v_stack)

h_stack = np.hstack((a, b))
print("Horizontal Stack:")
print(h_stack)

Vertical Stack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Horizontal Stack:
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [8]:
#4. Concatenate two arrays of different sizes along a new axis

In [9]:
x = np.array([1, 2, 3])
y = np.array([4, 5])

concatenated = np.array([x, y], dtype=object)

print("Concatenated (different sizes) along new axis:")
print(concatenated)

Concatenated (different sizes) along new axis:
[array([1, 2, 3]) array([4, 5])]


In [10]:
#5. Transpose a 3x2 matrix and reshape it to have 3 rows and 2 columns

In [11]:
original = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

transposed = original.T

reshaped = transposed.reshape(3, 2)

print("Transposed Matrix:")
print(transposed)

print("Reshaped to 3x2:")
print(reshaped)

Transposed Matrix:
[[1 3 5]
 [2 4 6]]
Reshaped to 3x2:
[[1 3]
 [5 2]
 [4 6]]
