In [1]:
#1.Create a 3x3 array filled with random integers between 0 and 10. Calculate the sum, mean, 
#and standard deviation of the array. 

In [2]:
import numpy as np

In [3]:
array = np.random.randint(0, 11, size=(3, 3))

print("Array:\n", array)

array_sum = np.sum(array)
array_mean = np.mean(array)
array_std = np.std(array)

print("Sum:", array_sum)
print("Mean:", array_mean)
print("Standard Deviation:", array_std)


Array:
 [[ 4  1  2]
 [ 2 10  3]
 [ 7  8  5]]
Sum: 42
Mean: 4.666666666666667
Standard Deviation: 2.9059326290271157


In [4]:
#2. Create a 1D array of 10 elements and compute the cumulative sum of the elements. 

In [5]:
array = np.random.randint(1, 11, size=10)

print("Original Array:", array)

cumulative_sum = np.cumsum(array)

print("Cumulative Sum:", cumulative_sum)


Original Array: [ 2  9  2  2  5  1  6  9  4 10]
Cumulative Sum: [ 2 11 13 15 20 21 27 36 40 50]


In [6]:
#3.Generate two 2x3 arrays with random integers and perform element-wise addition,subtraction, multiplication, and division. 

In [7]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(2, 3))

print("Array 1:\n", array1)
print("Array 2:\n", array2)

add = array1 + array2
subtract = array1 - array2
multiply = array1 * array2
divide = array1 / array2 

print("\nAddition:\n", add)
print("\nSubtraction:\n", subtract)
print("\nMultiplication:\n", multiply)
print("\nDivision:\n", divide)

Array 1:
 [[ 4  1 10]
 [ 5  1  3]]
Array 2:
 [[ 8  2 10]
 [ 1  8  7]]

Addition:
 [[12  3 20]
 [ 6  9 10]]

Subtraction:
 [[-4 -1  0]
 [ 4 -7 -4]]

Multiplication:
 [[ 32   2 100]
 [  5   8  21]]

Division:
 [[0.5        0.5        1.        ]
 [5.         0.125      0.42857143]]


In [8]:
#4. Create a 4x4 identity matrix. 

In [9]:
identity_matrix = np.identity(4)
print("4x4 Identity Matrix:\n", identity_matrix)

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
#5.Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.

In [11]:
a = np.array([5, 10, 15, 20, 25])

result = a / 5

print("Original array:", a)
print("Array after division by 5:", result)

Original array: [ 5 10 15 20 25]
Array after division by 5: [1. 2. 3. 4. 5.]
