In [1]:
#1.Create a 3x3 matrix and add a 1x3 array to each row using broadcasting

In [2]:
import numpy as np

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_array = np.array([10, 20, 30])

result = matrix + row_array
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [4]:
#2.Multiply a 1D array of 5 elements by a scalar value using broadcasting

In [5]:
array = np.array([1, 2, 3, 4, 5])
scalar = 10

result = array * scalar
print(result)

[10 20 30 40 50]


In [6]:
#3.Subtract a 3x1 column vector from a 3x3 matrix using broadcasting

In [7]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
column_vector = np.array([[1],
                          [2],
                          [3]])

result = matrix - column_vector
print(result)

[[ 9 19 29]
 [38 48 58]
 [67 77 87]]


In [8]:
#4. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions

In [9]:
array_3d = np.array([[[1, 2],
                      [3, 4]],
                     
                     [[5, 6],
                      [7, 8]]])

scalar = 5
result = array_3d + scalar
print(result)

[[[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


In [10]:
#5.Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting

In [11]:
a = np.array([[1], [2], [3], [4]])    
b = np.array([[10, 20, 30, 40, 50]])   

result = a + b
print(result)

[[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]
 [14 24 34 44 54]]
