In [1]:
#1.Extract elements at positions 2 to 10 with a step of 2

In [2]:
import numpy as np

In [3]:
arr = np.arange(15)
result = arr[2:11:2]
print("Extracted elements:", result)

Extracted elements: [ 2  4  6  8 10]


In [4]:
#2.Create a 5x5 matrix and extract a sub-matrix (rows 1 to 3, columns 2 to 4)

In [5]:
matrix = np.arange(25).reshape(5, 5)
sub_matrix = matrix[1:4, 2:5]
print("Original matrix:\n", matrix)
print("Sub-matrix:\n", sub_matrix)

Original matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Sub-matrix:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [6]:
#3.Replace all elements in a 1D array greater than 10 with the value 10

In [7]:
arr = np.array([4, 11, 7, 15, 3, 20, 9])
arr[arr > 10] = 10
print("Modified array:", arr)

Modified array: [ 4 10  7 10  3 10  9]


In [8]:
#3. Use fancy indexing to select elements at positions [0, 2, 4, 6]

In [9]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
indices = [0, 2, 4, 6]
selected = arr[indices]
print("Selected elements:", selected)

Selected elements: [10 30 50 70]


In [10]:
#4. Create a 1D array of 10 elements and reverse it using slicing

In [11]:
arr = np.arange(10)
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]
