In [1]:
#1.Create a 3x3 matrix and find its determinant

In [2]:
import numpy as np

In [3]:
A = np.array([[4, 2, 1],
              [3, 5, 7],
              [1, 1, 2]])

det = np.linalg.det(A)

print("Matrix A:\n", A)
print("Determinant of A:", det)

Matrix A:
 [[4 2 1]
 [3 5 7]
 [1 1 2]]
Determinant of A: 12.000000000000005


In [4]:
#2.Inverse of a 2x2 matrix and verify with identity matrix

In [5]:
B = np.array([[4, 7],
              [2, 6]])

B_inv = np.linalg.inv(B)

identity = np.dot(B, B_inv)

print("Matrix B:\n", B)
print("Inverse of B:\n", B_inv)
print("Product of B and B_inv (should be identity):\n", identity)

Matrix B:
 [[4 7]
 [2 6]]
Inverse of B:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Product of B and B_inv (should be identity):
 [[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


In [6]:
#3.Eigenvalues and eigenvectors of a 2x2 matrix

In [7]:
C = np.array([[2, 1],
              [1, 2]])


eigenvalues, eigenvectors = np.linalg.eig(C)

print("Matrix C:\n", C)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Matrix C:
 [[2 1]
 [1 2]]
Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [8]:
#4.Solve system of equations: 2x + 3y = 5 and 4x + 6y = 10

In [9]:
A = np.array([[2, 3],
              [4, 6]])
b = np.array([5, 10])

try:
    solution = np.linalg.solve(A, b)
    print("Solution [x, y]:", solution)
except np.linalg.LinAlgError as e:
    print("Cannot solve the system:", e)

Cannot solve the system: Singular matrix


In [10]:
#5.Perform SVD and reconstruct original matrix

In [11]:
D = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


U, S, Vt = np.linalg.svd(D)

S_matrix = np.zeros((3, 3))
S_matrix[:3, :3] = np.diag(S)

D_reconstructed = np.dot(U, np.dot(S_matrix, Vt))

print("Original Matrix D:\n", D)
print("U:\n", U)
print("Singular Values:", S)
print("Vt:\n", Vt)
print("Reconstructed Matrix:\n", D_reconstructed)

Original Matrix D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular Values: [1.68481034e+01 1.06836951e+00 3.33475287e-16]
Vt:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
Reconstructed Matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
