In [1]:
# 1. Normalize a NumPy array using Min-Max Scaling

In [2]:
import numpy as np

In [3]:
data = np.random.rand(10) * 100  

normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Original:", data)
print("Normalized:", normalized)

Original: [65.46122753 17.12207129 90.84255655 75.74766288 86.52049721 45.13644623
 73.6213045  23.42889066  9.0518024  41.57923733]
Normalized: [0.68967973 0.0986697  1.         0.81544499 0.94715712 0.44118243
 0.78944745 0.17577889 0.         0.39769085]


In [4]:
# 2. Replace values in a 5x5 random matrix

In [5]:
matrix = np.random.randint(1, 10, size=(5, 5)) 
print("Original matrix:\n", matrix)

matrix[matrix == 5] = 0
print("Modified matrix:\n", matrix)

Original matrix:
 [[8 1 3 3 7]
 [6 8 2 1 7]
 [5 5 4 6 8]
 [6 5 4 6 3]
 [9 2 6 4 2]]
Modified matrix:
 [[8 1 3 3 7]
 [6 8 2 1 7]
 [0 0 4 6 8]
 [6 0 4 6 3]
 [9 2 6 4 2]]


In [6]:
# 3. Element-wise operations

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [8]:
# 4.Solve a system of linear equations

In [9]:
A = np.array([[3, 4], [5, 2]])
B = np.array([7, 8])

solution = np.linalg.solve(A, B)
print("Solution [x, y]:", solution)

Solution [x, y]: [1.28571429 0.78571429]


In [10]:
# 5. Broadcasting with a 3x3 matrix and 1D array

In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
array = np.array([1, 0, -1])

result = matrix + array
print("Broadcasted Result:\n", result)

Broadcasted Result:
 [[2 2 2]
 [5 5 5]
 [8 8 8]]


In [12]:
# 6. Identity matrix

In [13]:
identity = np.eye(3)
print("3x3 Identity Matrix:\n", identity)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# 7. Matrix multiplication

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

product = np.dot(A, B)
print("Matrix Multiplication:\n", product)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [16]:
# 8. Dot and Cross product

In [17]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot_product = np.dot(v1, v2)
cross_product = np.cross(v1, v2)

print("Dot Product:", dot_product)
print("Cross Product:", cross_product)

Dot Product: 32
Cross Product: [-3  6 -3]


In [18]:
# 9. Find unique elements in an array

In [19]:
arr = np.random.randint(0, 10, size=20)
unique_elements = np.unique(arr)

print("Array:", arr)
print("Unique elements:", unique_elements)

Array: [5 2 7 7 7 2 9 0 1 0 7 6 3 0 0 4 0 5 8 7]
Unique elements: [0 1 2 3 4 5 6 7 8 9]


In [20]:
# 10. Function to return inverse of a matrix

In [21]:
def inverse_matrix(mat):
    try:
        return np.linalg.inv(mat)
    except np.linalg.LinAlgError:
        return "Matrix is singular and not invertible."

matrix = np.array([[4, 7], [2, 6]])
print("Inverse of matrix:\n", inverse_matrix(matrix))

Inverse of matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
