In [1]:
#1.Compute the square root of each element in a 2D array using vectorized operations

In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 4, 9], [16, 25, 36]])


sqrt_arr = np.sqrt(arr)

print("Original Array:\n", arr)
print("Square Root Array:\n", sqrt_arr)

Original Array:
 [[ 1  4  9]
 [16 25 36]]
Square Root Array:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
#2.Calculate the dot product of two 1D arrays of size 5

In [5]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

dot_product = np.dot(a, b)

print("Array A:", a)
print("Array B:", b)
print("Dot Product:", dot_product)

Array A: [1 2 3 4 5]
Array B: [5 4 3 2 1]
Dot Product: 35


In [6]:
#3.Perform element-wise comparison of two 1D arrays and return an array of boolean values 
#where the first array has larger elements

In [7]:
a = np.array([5, 10, 15])
b = np.array([3, 12, 10])

comparison = a > b

print("Array A:", a)
print("Array B:", b)
print("Comparison (A > B):", comparison)

Array A: [ 5 10 15]
Array B: [ 3 12 10]
Comparison (A > B): [ True False  True]


In [8]:
#4.Create a 2D array and apply a vectorized operation to double the value of each element

In [9]:
arr = np.array([[1, 2], [3, 4]])
doubled = arr * 2

print("Original Array:\n", arr)
print("Doubled Array:\n", doubled)

Original Array:
 [[1 2]
 [3 4]]
Doubled Array:
 [[2 4]
 [6 8]]


In [10]:
#5.Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations

In [11]:
arr = np.random.randint(1, 101, size=100)

even_numbers = arr[arr % 2 == 0]

even_sum = np.sum(even_numbers)

print("Random Array:\n", arr)
print("Even Numbers:\n", even_numbers)
print("Sum of Even Numbers:", even_sum)

Random Array:
 [ 33  37  32  46  43  77  45  85  17  57   2  26  29  23  25  73  40  82
  68   1  37  61  41  50  58  60  79  19  48  26 100  85   8  37  19   5
   8   6  41  46  45  74  18  83  13  64  27   9  11  20  47  92  23  10
  89  83  51  22  90   7  57  16  37  79  62  45  11  20  75  58  17  96
  93  22  56   1  97  91  99   4  95  18  16  81   5 100  74  49  87  77
  21  43  20  14   4  62  29  95  30   5]
Even Numbers:
 [ 32  46   2  26  40  82  68  50  58  60  48  26 100   8   8   6  46  74
  18  64  20  92  10  22  90  16  62  20  58  96  22  56   4  18  16 100
  74  20  14   4  62  30]
Sum of Even Numbers: 1768
